name: 'Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

  
jobs:
  LogInToAWS:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

  Terraform:
    runs-on: ubuntu-latest
    needs: LogInToAWS
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -input=false
    - name: Apply Terraform configuration
      run: terraform apply -auto-approve
